// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SchoolApi;

namespace SchoolApi.Migrations
{
    [DbContext(typeof(SchoolContext))]
    [Migration("20210908063721_fourthMigration")]
    partial class fourthMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.9")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SchoolApi.Models.DataEntry", b =>
                {
                    b.Property<int>("RoomNumber")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("HumId")
                        .HasColumnType("int");

                    b.Property<int>("PhotoResistorId")
                        .HasColumnType("int");

                    b.HasKey("RoomNumber", "CreatedTime");

                    b.ToTable("DataEntry");
                });

            modelBuilder.Entity("SchoolApi.Models.HumidityTempSensor", b =>
                {
                    b.Property<int>("HumId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime?>("DataEntryCreatedTime")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DataEntryRoomNumber")
                        .HasColumnType("int");

                    b.Property<float>("Humidity")
                        .HasColumnType("real");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<float>("Temperature")
                        .HasColumnType("real");

                    b.Property<DateTime>("TimeOccured")
                        .HasColumnType("datetime2");

                    b.HasKey("HumId");

                    b.HasIndex("DataEntryRoomNumber", "DataEntryCreatedTime");

                    b.ToTable("HumidityTempSensor");
                });

            modelBuilder.Entity("SchoolApi.Models.PhotoResistor", b =>
                {
                    b.Property<int>("PhotoResistorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime?>("DataEntryCreatedTime")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DataEntryRoomNumber")
                        .HasColumnType("int");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<int>("LightLevel")
                        .HasColumnType("int");

                    b.Property<DateTime>("TimeOccured")
                        .HasColumnType("datetime2");

                    b.HasKey("PhotoResistorId");

                    b.HasIndex("DataEntryRoomNumber", "DataEntryCreatedTime");

                    b.ToTable("PhotoResistor");
                });

            modelBuilder.Entity("SchoolApi.Models.HumidityTempSensor", b =>
                {
                    b.HasOne("SchoolApi.Models.DataEntry", null)
                        .WithMany()
                        .HasForeignKey("HumId")
                        .HasPrincipalKey("HumId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SchoolApi.Models.DataEntry", null)
                        .WithMany("HumidityTempSensor")
                        .HasForeignKey("DataEntryRoomNumber", "DataEntryCreatedTime");
                });

            modelBuilder.Entity("SchoolApi.Models.PhotoResistor", b =>
                {
                    b.HasOne("SchoolApi.Models.DataEntry", null)
                        .WithMany()
                        .HasForeignKey("PhotoResistorId")
                        .HasPrincipalKey("PhotoResistorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SchoolApi.Models.DataEntry", null)
                        .WithMany("PhotoResistor")
                        .HasForeignKey("DataEntryRoomNumber", "DataEntryCreatedTime");
                });

            modelBuilder.Entity("SchoolApi.Models.DataEntry", b =>
                {
                    b.Navigation("HumidityTempSensor");

                    b.Navigation("PhotoResistor");
                });
#pragma warning restore 612, 618
        }
    }
}
