// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SchoolApi;

namespace SchoolApi.Migrations
{
    [DbContext(typeof(SchoolContext))]
    partial class SchoolContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.9")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SchoolApi.Models.DataEntry", b =>
                {
                    b.Property<string>("RoomNumber")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("HumidId")
                        .HasColumnType("int");

                    b.Property<int>("PhotoResId")
                        .HasColumnType("int");

                    b.HasKey("RoomNumber", "CreatedTime");

                    b.HasIndex("HumidId");

                    b.HasIndex("PhotoResId");

                    b.ToTable("DataEntry");
                });

            modelBuilder.Entity("SchoolApi.Models.HumidityTempSensor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<float>("Humidity")
                        .HasColumnType("real");

                    b.Property<float>("Temperature")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.ToTable("HumidityTempSensor");
                });

            modelBuilder.Entity("SchoolApi.Models.PhotoResistor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("LightLevel")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("PhotoResistor");
                });

            modelBuilder.Entity("SchoolApi.Models.DataEntry", b =>
                {
                    b.HasOne("SchoolApi.Models.HumidityTempSensor", "HumidityTempSensor")
                        .WithMany()
                        .HasForeignKey("HumidId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SchoolApi.Models.PhotoResistor", "PhotoResistor")
                        .WithMany()
                        .HasForeignKey("PhotoResId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HumidityTempSensor");

                    b.Navigation("PhotoResistor");
                });
#pragma warning restore 612, 618
        }
    }
}
